export default class ErrorCodes {
    static MISSING_HEADERS= "MISSING_HEADERS";
    static MISSING_PARAMETERS= "MISSING_PARAMETERS";
    static INVALID_METHOD= "INVALID_METHOD";
    static INVALID_SMS_CODE= "INVALID_SMS_CODE";
    static DISABLED_USER= "DISABLED_USER";
    static INVALID_USER= "INVALID_USER";
    static INVALID_PASSWORD= "INVALID_PASSWORD";
    static PATH_VERIFY_ERROR= "PATH_VERIFY_ERROR";
    static INVALID_TOKEN= "INVALID_TOKEN";
    static SERVER_ERROR= "SERVER_ERROR";
    static PHONE_NUMBER_EXISTS= "PHONE_NUM_EXISTS";
    static VEHICLE_NOT_FOUND= "VEHICLE_NOT_FOUND";
    static PHOTO_NOT_FOUND= "PHOTO_NOT_FOUND";
    static AUTHORIZATION_ERROR= "AUTHORIZATION_ERROR";
    static OPERATION_NOT_FOUND= "OPERATION_NOT_FOUND";
    static OPERATION_AVAIBLE= "OPERATION_AVAIBLE";
    static NOTE_NOT_FOUND= "NOTE_NOT_FOUND";
    static OFFER_NOT_FOUND= "OFFER_NOT_FOUND";
}