const ErrorCodes = Object.freeze({
    MISSING_HEADERS: "MISSING_HEADERS",
    MISSING_PARAMETERS: "MISSING_PARAMETERS",
    INVALID_METHOD: "INVALID_METHOD",
    INVALID_SMS_CODE: "INVALID_SMS_CODE",
    DISABLED_USER: "DISABLED_USER",
    INVALID_USER: "INVALID_USER",
});

export default ErrorCodes;